apiVersion: v1
kind: Pod
metadata:
    name: pod-dos-contenedores
spec:
    containers:
    - name: contenedor1
      image: nginx:alpine
    - name: contenedor2
      image: python:3.6-alpine
      command: ['sh', '-c',  'echo "contenedor-2" > index.html && python -m http.server 8080']