apiVersion: v1
kind: Pod
metadata:
    name: pod-front
    labels: 
      app: front
spec:
    containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasettest
  labels:
    app: replicasettest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata: 
      labels:
        app: front
    spec:
      containers:
      - name: server
        image: nginx:alpine