apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasettest
  labels:
    app: replicasettest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata: 
      labels:
        app: front
    spec:
      containers:
      - name: server
#        image: nginx:1.21.0
        image: nginx:alpine
